title: The Long Way Around
permalink: /:year/:month/:title

plugins: [jekyll-paginate]

paginate: 5
paginate_path: "page:num"

description: It's not about the destination, it's about the journey

exclude: [node_modules, README.md, CNAME, .gitignore, .git, _sass ]
keep_files: [images]

# values used on index page
distance: 24820
boats: 9
trains: 24
buses: 12