title: The Long Way Around
permalink: /:year/:month/:title

gems: [jekyll-paginate]

paginate: 5
paginate_path: "page:num"

description: It's not about the destination, it's about the journey

include: ['images']