# Welcome to Jekyll!
#

# Site settings
title: The Long Way Around
description: |
  Some stuff here about our travels
owner: Kat Moon / Jack Le Riche
first_published: 2016 # if migrating another site, the year of your first publish
email: jackleriche@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thelongwayaround.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/jackleriche
  github: https://github.com/jackleriche
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
